#!/usr/bin/with-contenv bash

cd /app/synclounge || exit

WEB_ACCESSURL=${DOMAIN:-$(curl icanhazip.com)}
SERVERS=${</defaults/server.json}
AUTHENTICATION=${</defaults/authentication.json}

exec \
	s6-setuidgid abc node webapp.js
