#!/usr/bin/with-contenv bash

DOMAIN=${DOMAIN:-$(curl icanhazip.com)}

sed -i "s|SERVERURL|http://${DOMAIN}|g" /defaults/servers.json

if [ -n "$AUTH_USERS" ]; then
    AUTH_USERS=$(echo $AUTH_USERS | sed 's|,|",\\n    "|g')
    sed -i "s|AUTH_USERS|$AUTH_USERS|g" /defaults/authentication.json
fi

# permissions
chown -R abc:abc \
	/app
