#!/usr/bin/with-contenv bash

EXTERNAL_URL=${EXTERNAL_URL:-$(curl icanhazip.com)}
if [ -n "$EXTERNAL_SERVER_PORT" ]; then
    sed -i "s|SERVERURL|http://${EXTERNAL_URL}:${EXTERNAL_SERVER_PORT}|g" /defaults/servers.json
else
    sed -i "s|SERVERURL|http://${EXTERNAL_URL}|g" /defaults/servers.json
fi

if [ -n "$AUTH_USERS" ]; then
    AUTH_USERS=$(echo $AUTH_USERS | sed 's|,|",\\n    "|g')
    sed -i "s|AUTH_USERS|$AUTH_USERS|g" /defaults/authentication.json
fi

# permissions
chown -R abc:abc \
    /app
